# Generated by Django 4.2.16 on 2024-09-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='requirements',
            field=models.TextField(blank=True),
        ),
    ]
