# Generated by Django 4.2.16 on 2024-09-23 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_reservation_requirements'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['reservation_date', 'reservation_time']},
        ),
    ]
