# Generated by Django 4.2.16 on 2024-09-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beverages',
            name='title',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='title',
            field=models.CharField(),
        ),
    ]
